// This file is auto-generated by @hey-api/openapi-ts

import type { GetAllUsersResponse } from './types.gen';

const userResponseSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    if (data.deletedAt) {
        data.deletedAt = new Date(data.deletedAt);
    }
    return data;
};

const getUsersResponseSchemaResponseTransformer = (data: any) => {
    data.data = data.data.map((item: any) => {
        return userResponseSchemaResponseTransformer(item);
    });
    return data;
};

export const getAllUsersResponseTransformer = async (data: any): Promise<GetAllUsersResponse> => {
    data = getUsersResponseSchemaResponseTransformer(data);
    return data;
};